/**
 * mockup 各頁 header 的 active 狀態（自 mockup/*.html 逐頁擷取，未經推論）。
 * key = 路由 slug（首頁為 ''），值 = [頂層項 slug, 下拉子項 slug?]
 */
export const NAV_ACTIVE: Record<string, [string, string?]> = {
  'about-difference': ['differences', 'about-difference'],
  'about-benefits': ['differences', 'about-benefits'],
  'about-certifications': ['differences', 'about-certifications'],
  differences: ['differences'],
  facility: ['differences', 'facility'],
  'facility-pre-press': ['differences', 'facility'],
  'facility-eco-printing': ['differences', 'facility'],
  'facility-post-press': ['differences', 'facility'],
  'facility-quality': ['differences', 'facility'],
  'facility-tour': ['differences', 'facility'],
  'printing-solutions': ['printing-solutions'],
  'colorbox': ['printing-solutions', 'colorbox'],
  'cardboard': ['printing-solutions', 'cardboard'],
  'uv-printing': ['printing-solutions', 'uv-printing'],
  'other-printing': ['printing-solutions', 'other-printing'],
  'printing-projects': ['printing-projects'],
  'green-advantage': ['green-advantage'],
  'green-our-advantage': ['green-advantage', 'green-our-advantage'],
  'green-carbon': ['green-advantage', 'green-carbon'],
  'green-materials': ['green-advantage', 'green-materials'],
  'green-esg': ['green-advantage', 'green-esg'],
  insights: ['insights'],
  news: ['insights', 'news'],
  'blog': ['insights', 'blog'],
  faq: ['insights', 'faq'],
  'printing-trends': ['insights', 'printing-trends'],
  'news-animals-of-tomorrow': ['insights', 'news'],
  'news-commonwealth-interview': ['insights', 'news'],
  'news-firefighter-boardgame': ['insights', 'news'],
  'news-gentle-wild-paper-bags': ['insights', 'news'],
  'news-global-views-esg-award': ['insights', 'news'],
  'news-green-drive-seminar': ['insights', 'news'],
  'news-green-printing-digital-innovation': ['insights', 'news'],
  'news-hp-variable-data-printing': ['insights', 'news'],
  'news-low-carbon-production-film': ['insights', 'news'],
  'news-national-sustainable-development-award': ['insights', 'news'],
  'news-sme-investment-benchmark': ['insights', 'news'],
  'news-taicca-partnership': ['insights', 'news'],
  // 首頁、careers、contact、get-a-quote、privacy-legal、supplier-area 在 mockup 中無 active
}
