/**
 * `zh.ts` 的精簡子集，只給 client component 用（header 與兩個 explorer）。
 *
 * **由 `node scripts/extract-i18n.mjs --client` 產生，不要手改。**
 * 分成兩份純粹是為了不要把整本字典打進 client bundle，理由見 `lib/translate.tsx`。
 */
export const ZH_CLIENT: Record<string, string> = {
  "A daily-use gift for festivals, corporate gifting, and advertising promotion.": "適合節慶、企業贈禮與廣告促銷的日常實用贈品。",
  "About Us": "關於我們",
  "Automatic heat shrink wrap machine": "自動熱收縮包裝機",
  "Axis Control color measurement system": "Axis Control 色彩量測系統",
  "Backcards for blister vacuum packaging — hand tools, electronic spare parts, and automotive components.": "真空泡殼包裝用的背卡 —— 手工具、電子備品與汽車零組件。",
  "Barcode grade scanner": "條碼等級檢測儀",
  "Benefits to Clients": "客戶得到的效益",
  "Blister Cardboard": "泡殼紙板",
  "Blister packing strength tester": "泡殼包裝強度試驗機",
  "Bottom Gluing Box": "黏底盒",
  "Carbon Efficiency": "碳效率",
  "Case Studies & Photos": "案例與實拍",
  "Certifications, Partnerships & Awards": "認證、夥伴與獲獎",
  "Color Box Packaging": "彩盒包裝",
  "Corporate Gifts | Festival Promotion | Brand Merchandising": "企業贈品 | 節慶促銷 | 品牌商品",
  "Customized structural design and material suggestions for shapes beyond the standard catalogue.": "針對標準型錄以外的形狀，提供客製化結構設計與材料建議。",
  "Desk Calendars": "桌曆",
  "Digital window patching machine": "數位貼窗機",
  "ECO Materials": "環保材料",
  "ESG & Future Goals": "ESG 與未來目標",
  "Electronics | Electrical Appliances | Hardware | Auto Parts": "電子 | 電器 | 五金 | 汽車零件",
  "FAQ": "常見問題",
  "Facilities & Equipment": "設備與廠房",
  "Factory floor": "廠區現場",
  "Foil embossing and logical-light embossment — custom-developed finishes that protect and elevate your brand.": "燙金壓凸與雷射光影壓紋 —— 專為保護並提升品牌而開發的加工。",
  "Food | Electronics | Beauty | Medical | Luxury | Consumer Goods": "食品 | 電子 | 美妝 | 醫療 | 精品 | 消費性產品",
  "Four latches in a crossed structure add loading strength — easy to assemble and more economical.": "四爪交叉結構提升承載強度 —— 容易組裝也更經濟。",
  "Gloss meter — Elcometer 406": "光澤度計 —— Elcometer 406",
  "Glued bottom carries more weight while staying easy to assemble — the choice for heavier products.": "黏合底部能承載更多重量，同時保持易組裝 —— 較重產品的首選。",
  "Glued or crossed bottom with a built-in handle — no extra carrier bag needed. Popular for gift boxes, cakes, and takeaway.": "黏底或交叉底並內建提把 —— 不需另外的提袋。常見於禮盒、蛋糕與外帶。",
  "Gluing Box": "糊盒",
  "Green Vlog": "綠色 Vlog",
  "Hand Bags": "手提袋",
  "Hand-Carry Box": "手提盒",
  "Heidelberg Speedmaster CD-102 press line": "海德堡 Speedmaster CD-102 印刷產線",
  "Heidelberg Suprasetter 105 S CTP": "海德堡 Suprasetter 105 S CTP",
  "Heidelberg Varimatrix 105 die-cutter": "海德堡 Varimatrix 105 模切機",
  "High-speed intelligent laminating machine": "高速智慧型貼合機",
  "High-speed universal folder-gluer": "高速萬用糊盒機",
  "Image Control spectral measurement": "Image Control 光譜量測",
  "Industries / Applications": "產業與應用",
  "Industry Trends": "產業趨勢",
  "Ink rub tester": "油墨耐磨試驗機",
  "Insert Bottom Box": "插底盒",
  "Insights": "洞察",
  "Instructions & Catalogs": "說明書與型錄",
  "Jazzy Light color management system": "Jazzy Light 色彩管理系統",
  "Latest News": "最新消息",
  "Litho printing on non-absorbent materials — instant ink curing means post-finishing can start immediately, with no backprint, shorter lead times, and lower cost.": "在非吸收性材質上的平版印刷 —— 油墨瞬間固化，印後加工可立即開始，不會背印，交期更短、成本更低。",
  "Menu": "選單",
  "Mouse Pads": "滑鼠墊",
  "NTI Printing home": "NTI Printing 首頁",
  "Other Printing": "其他印刷",
  "Our Green Advantages": "我們的綠色優勢",
  "PE / PVC / PP Films | Metal Foils | Glossy Cardboard": "PE／PVC／PP 膜 | 金屬箔 | 亮面紙板",
  "Packaging Paperboard": "包裝紙板",
  "Packaging stock & logistics": "包裝庫存與物流",
  "Paper Hang Tags & Blister Backcards": "紙製吊卡與泡殼背卡",
  "Paper, plastic, or textile carrier bags that promote products and strengthen brand image.": "紙質、塑膠或織品提袋，推廣產品同時強化品牌形象。",
  "Press room — production control": "印刷現場 —— 生產控管",
  "Prinect Color Proof Pro — digital proofing": "Prinect Color Proof Pro —— 數位打樣",
  "Product manuals and catalogs — functions, usage, instructions, and precautions.": "產品說明書與型錄 —— 功能、使用方式、操作說明與注意事項。",
  "Production aisle": "生產動線",
  "Projects": "實績案例",
  "Red Envelopes": "紅包袋",
  "Separate lid and base — a more complex structure with an elegant, premium presentation.": "盒蓋與盒身分離 —— 結構較複雜，呈現優雅高階的質感。",
  "Solutions": "解決方案",
  "Special Package": "特殊包裝",
  "Special Printing & Anti-Counterfeiting": "特殊印刷與防偽",
  "Strong seasonal impact through graphic design and heat-emboss finishing.": "以平面設計與燙金壓凸創造強烈的節慶效果。",
  "Sustainability": "永續",
  "Temperature & humidity chamber": "恆溫恆濕試驗機",
  "The NTI Difference": "NTI 的與眾不同",
  "The most common box type — top and bottom open, easy to assemble, and suited to lighter products.": "最常見的盒型 —— 上下開口、容易組裝，適合較輕的產品。",
  "Top & Bottom Box": "天地蓋盒",
  "Two cardboards laminated with one blister — protective display packaging for retail products.": "兩片紙板貼合一個泡殼 —— 零售商品的保護型陳列包裝。",
  "UV Printing": "UV 印刷",
  "UV-printed for color saturation and long-lasting fade resistance.": "採 UV 印刷，色彩飽和、抗褪色持久。",
  "X-Rite IC Plate II dot measurement": "X-Rite IC Plate II 網點量測",
  "X-Rite eXact spectrophotometer": "X-Rite eXact 分光光度計",
  "X-Rite i1iO spectral color measurement": "X-Rite i1iO 光譜色彩量測",
  "ZÜND CCD high-speed cutter": "ZÜND CCD 高速切割機",
}
